<?php

namespace AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findOrderBySurname(){
        $em = $this->getEntityManager();
        $query = $em->createQuery("SELECT p FROM AddressBookBundle:Person p ORDER BY p.surname ASC");
        $persons = $query->getResult();
        return $persons;
    }
}
